name: "Spring Boot Deploy"
description: "Build and deploy Spring Boot app to EC2"
runs:
  using: "composite"
  steps:
    - name: Build with Maven
      run: mvn clean package -DskipTests
      shell: bash

    - name: Copy JAR to EC2
      run: |
        scp -i ${{ secrets.EC2_KEY }} target/*.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app.jar
      shell: bash

    - name: Run Spring Boot app on EC2
      run: |
        ssh -i ${{ secrets.EC2_KEY }} ubuntu@${{ secrets.EC2_HOST }} \
        "nohup java -jar /home/ubuntu/app.jar > app.log 2>&1 &"
      shell: bash

