name: 'Spring Boot Deploy'
description: 'Deploy Spring Boot JAR to EC2'

inputs:
  ec2_key:
    description: 'EC2 private key'
    required: true
  ec2_user:
    description: 'EC2 user'
    required: true
  ec2_host:
    description: 'EC2 host'
    required: true

runs:
  using: "composite"
  steps:
    - name: Write EC2 key
      shell: bash
      run: |
        echo "${{ inputs.ec2_key }}" > ec2-key.pem
        chmod 600 ec2-key.pem

    - name: Upload Spring Boot JAR to EC2
      shell: bash
      run: |
        echo "Uploading Spring Boot JAR..."
        scp -o StrictHostKeyChecking=no -i ec2-key.pem target/*.jar ${{ inputs.ec2_user }}@${{ inputs.ec2_host }}:/home/${{ inputs.ec2_user }}/

    - name: Restart Spring Boot App
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ inputs.ec2_user }}@${{ inputs.ec2_host }} "pkill -f 'java -jar' || true; nohup java -jar /home/${{ inputs.ec2_user }}/*.jar > app.log 2>&1 &"

