y
name: Spring Boot Deploy
description: "Build and deploy Spring Boot app to EC2 using systemd"

inputs:
  host:
    required: true
  username:
    required: true
  key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Build with Maven
      run: mvn clean package -DskipTests
      shell: bash

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        source: "target/demo-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/demo-0.0.1-SNAPSHOT.jar"

    - name: Restart systemd service
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        key: ${{ inputs.key }}
        script: |
          sudo systemctl stop myapp || true
          sudo systemctl start myapp
          sudo systemctl status myapp --no-pager
