name: "Spring Boot Deploy"
description: "Deploy Spring Boot app to EC2"

inputs:
  ec2_key:
    description: "EC2 private key"
    required: true
  ec2_host:
    description: "EC2 host address"
    required: true
  ec2_user:
    description: "EC2 username"
    required: true

runs:
  using: "composite"
  steps:
    - name: Save EC2 key
      shell: bash
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
        chmod 600 ec2-key.pem

    - name: Copy JAR to EC2
      shell: bash
      run: |
        scp -o StrictHostKeyChecking=no -i ec2-key.pem target/*.jar \
        ${{ inputs.ec2_user }}@${{ inputs.ec2_host }}:/home/${{ inputs.ec2_user }}/app.jar

    - name: Run JAR on EC2
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ inputs.ec2_user }}@${{ inputs.ec2_host }} "
          nohup java -jar /home/${{ inputs.ec2_user }}/app.jar > app.log 2>&1 &
        "

