name: "Spring Boot Deploy"
description: "Deploys a Spring Boot JAR to EC2"

inputs:
  ec2_user:
    description: "EC2 username"
    required: true
  ec2_host:
    description: "EC2 public IP or DNS"
    required: true
  ec2_key:
    description: "Private SSH key for EC2"
    required: true

runs:
  using: "composite"
  steps:
    - name: Save EC2 key
      shell: bash
      run: |
        echo "${{ inputs.ec2_key }}" > ec2-key.pem
        chmod 600 ec2-key.pem

    - name: Copy JAR to EC2
      shell: bash
      run: |
        scp -o StrictHostKeyChecking=no -i ec2-key.pem target/*.jar \
        ${{ inputs.ec2_user }}@${{ inputs.ec2_host }}:/home/${{ inputs.ec2_user }}/app.jar

    - name: Run JAR on EC2
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ inputs.ec2_user }}@${{ inputs.ec2_host }} "
          nohup java -jar /home/${{ inputs.ec2_user }}/app.jar > app.log 2>&1 &
        "

